package com.xstudio.rest.vo;

import com.alibaba.fastjson.annotation.JSONField;
import com.xstudio.crm.model.Customer;
import com.xstudio.crm.model.CustomerContacts;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author xiaobiao
 * @version 2019/6/4
 */
@Data
public class CustomerPool implements Serializable {

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     * Database Column Remarks:
     *   客户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date createAt;
}
