spring:
  quartz:
    group: 'crm'
    instanceName: crmQuartzScheduler
  session:
    store-type: none
  datasource:
    druid:
      crm:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/crm?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true
        username: root
        password: "123456"
        type: com.alibaba.druid.pool.DruidDataSource
        db-type: mysql
        # 初始化时建立物理连接的个数
        initial-size: 5
        # 最小连接池数量
        min-idle: 5
        # 最大连接池数量 maxIdle已经不再使用
        max-active: 20
        # 获取连接时最大等待时间，单位毫秒
        max-wait: 60000
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-while-idle: true
        # 既作为检测的间隔时间又作为testWhileIdel执行的依据
        time-between-eviction-runs-millis: 60000
        # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
        min-evictable-idle-time-millis: 30000
        # 用来检测连接是否有效的sql 必须是一个查询语句
        # mysql中为 select 'x'
        # oracle中为 select 1 from dual
        validation-query: select 'x'
        # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-borrow: false
        # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-return: false
        # 当数据库抛出不可恢复的异常时,抛弃该连接
        # exception-sorter: true
        # 是否缓存preparedStatement,mysql5.5+建议开启
        pool-prepared-statements: true
        # 当值大于0时poolPreparedStatements会自动修改为true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置扩展插件
        filters: stat,wall
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
        # 设置访问druid监控页的账号和密码,默认没有
        stat-view-servlet:
          login-username: admin
          login-password: adminxxxxxxx
      quartz:
        url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&allowMultiQueries=true&autoReconnect=true
        username: root
        password: "123456"
        maxConnections: 5
        validationQuery: select 0
        db-type: mysql
        # 初始化时建立物理连接的个数
        initial-size: 5
        # 最小连接池数量
        min-idle: 5
        # 最大连接池数量 maxIdle已经不再使用
        max-active: 20
        # 获取连接时最大等待时间，单位毫秒
        max-wait: 60000
        # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        test-while-idle: true
        # 既作为检测的间隔时间又作为testWhileIdel执行的依据
        time-between-eviction-runs-millis: 60000
        # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
        min-evictable-idle-time-millis: 30000
        # 用来检测连接是否有效的sql 必须是一个查询语句
        # mysql中为 select 'x'
        # oracle中为 select 1 from dual
        validation-query: select 'x'
        # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-borrow: false
        # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
        test-on-return: false
        # 当数据库抛出不可恢复的异常时,抛弃该连接
        # exception-sorter: true
        # 是否缓存preparedStatement,mysql5.5+建议开启
        pool-prepared-statements: true
        # 当值大于0时poolPreparedStatements会自动修改为true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置扩展插件
        filters: stat,wall
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
        # 设置访问druid监控页的账号和密码,默认没有
        stat-view-servlet:
          login-username: admin
          login-password: adminxxxxxxx
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mybatis/**/**.xml
  type-aliases-package: com.xstudio.crm.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30


logging:
  level:
    root: debug
  config: classpath:log4j2.yml
