package com.xstudio.crm.model;

import com.xstudio.tool.utils.BaseModelObject2;
import java.io.Serializable;
import java.math.BigDecimal;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer_ruzhu
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CustomerRuzhu extends BaseModelObject2<Long> implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.ruzhu_id
     *
     * @mbg.generated
     */
    private Long ruzhuId;

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     * Database Column Remarks:
     *   入驻园区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.yuanqu
     *
     * @mbg.generated
     */
    private String yuanqu;

    /**
     * Database Column Remarks:
     *   入驻企业名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * Database Column Remarks:
     *   母公司
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.main_company
     *
     * @mbg.generated
     */
    private String mainCompany;

    /**
     * Database Column Remarks:
     *   招商人员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.zhao_shang
     *
     * @mbg.generated
     */
    private String zhaoShang;

    /**
     * Database Column Remarks:
     *   法人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.fa_ren
     *
     * @mbg.generated
     */
    private String faRen;

    /**
     * Database Column Remarks:
     *   法人身份证号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.fa_ren_idcard
     *
     * @mbg.generated
     */
    private String faRenIdcard;

    /**
     * Database Column Remarks:
     *   法人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.fa_ren_mobile
     *
     * @mbg.generated
     */
    private String faRenMobile;

    /**
     * Database Column Remarks:
     *   注册资金（万元）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.registered_capital
     *
     * @mbg.generated
     */
    private BigDecimal registeredCapital;

    /**
     * Database Column Remarks:
     *   投资比例（如比例不为100%，请完善其他投资者信息）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.investment
     *
     * @mbg.generated
     */
    private BigDecimal investment;

    /**
     * Database Column Remarks:
     *   对接人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.dui_jie_ren
     *
     * @mbg.generated
     */
    private String duiJieRen;

    /**
     * Database Column Remarks:
     *   对接人电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.dui_jie_ren_mobile
     *
     * @mbg.generated
     */
    private String duiJieRenMobile;

    /**
     * Database Column Remarks:
     *   代账或财务姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.financial_name
     *
     * @mbg.generated
     */
    private String financialName;

    /**
     * Database Column Remarks:
     *   代账或财务电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.financial_mobile
     *
     * @mbg.generated
     */
    private String financialMobile;

    /**
     * Database Column Remarks:
     *   网上税务局账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.suiwu_account
     *
     * @mbg.generated
     */
    private String suiwuAccount;

    /**
     * Database Column Remarks:
     *   网上税务局密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.suiwu_password
     *
     * @mbg.generated
     */
    private String suiwuPassword;

    /**
     * Database Column Remarks:
     *   个人所得税APP账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.app_account
     *
     * @mbg.generated
     */
    private String appAccount;

    /**
     * Database Column Remarks:
     *   个人所得税APP密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.app_password
     *
     * @mbg.generated
     */
    private String appPassword;

    /**
     * Database Column Remarks:
     *   开票品目（主行业）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.kaipiao_type
     *
     * @mbg.generated
     */
    private String kaipiaoType;

    /**
     * Database Column Remarks:
     *   开户行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.kai_hu_hang
     *
     * @mbg.generated
     */
    private String kaiHuHang;

    /**
     * Database Column Remarks:
     *   银行账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.bank_number
     *
     * @mbg.generated
     */
    private String bankNumber;

    /**
     * Database Column Remarks:
     *   是否已签订入驻协议
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.agreement
     *
     * @mbg.generated
     */
    private Boolean agreement;

    /**
     * Database Column Remarks:
     *   是否需要买盘
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.mai_pan
     *
     * @mbg.generated
     */
    private Boolean maiPan;

    /**
     * Database Column Remarks:
     *   开具专票还是普票
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.tick_type
     *
     * @mbg.generated
     */
    private String tickType;

    /**
     * Database Column Remarks:
     *   目前进度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_ruzhu.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_ruzhu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Long key) {
        this.ruzhuId = key;
    }

    @Override
    public Long getKey() {
        return ruzhuId;
    }
}