package com.xstudio.crm.model;

import com.xstudio.tool.utils.BaseModelObject2;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer_contacts
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CustomerContacts extends BaseModelObject2<Long> implements Serializable {
    /**
     * Database Column Remarks:
     *   联系人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.contacts_id
     *
     * @mbg.generated
     */
    private Long contactsId;

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     * Database Column Remarks:
     *   联系人职务
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.contact_duties
     *
     * @mbg.generated
     */
    private String contactDuties;

    /**
     * Database Column Remarks:
     *   联系人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.contact_name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     * Database Column Remarks:
     *   联系人方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_contacts.contact_mobile
     *
     * @mbg.generated
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_contacts
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Long key) {
        this.contactsId = key;
    }

    @Override
    public Long getKey() {
        return contactsId;
    }
}