package com.xstudio.crm.model;

import com.xstudio.tool.utils.BaseModelObject2;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer_user_log
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CustomerUserLog extends BaseModelObject2<Long> implements Serializable {
    /**
     * Database Column Remarks:
     *   日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_user_log.contacts_id
     *
     * @mbg.generated
     */
    private Long contactsId;

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_user_log.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_user_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Long key) {
        this.contactsId = key;
    }

    @Override
    public Long getKey() {
        return contactsId;
    }
}