package com.xstudio.crm.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.xstudio.tool.utils.BaseModelObject2;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class Customer extends BaseModelObject2<Long> implements Serializable {

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     * Database Column Remarks:
     *   客户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     * Database Column Remarks:
     *   联系地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   所属行业
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.industry
     *
     * @mbg.generated
     */
    private Long industry;

    /**
     * Database Column Remarks:
     *   客户来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.source
     *
     * @mbg.generated
     */
    private Long source;

    /**
     * Database Column Remarks:
     *   当前负责ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.principal_id
     *
     * @mbg.generated
     */
    private Long principalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date ownedAtBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date ownedAtEnd;

    /**
     * Database Column Remarks:
     *   领用时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.owned_at
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date ownedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Long key) {
        this.customerId = key;
    }

    @Override
    public Long getKey() {
        return customerId;
    }
}
