package com.xstudio.crm.model;

import com.alibaba.fastjson.annotation.JSONField;
import com.xstudio.tool.utils.BaseModelObject2;
import java.io.Serializable;
import java.util.Date;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table customer_follow_up
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class CustomerFollowUp extends BaseModelObject2<Long> implements Serializable {
    /**
     * Database Column Remarks:
     *   ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.customer_id
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     * Database Column Remarks:
     *   联系人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.contact_name
     *
     * @mbg.generated
     */
    private String contactName;

    /**
     * Database Column Remarks:
     *   联系人方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.contact_mobile
     *
     * @mbg.generated
     */
    private String contactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_follow_up
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date followUpDateBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_follow_up
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date followUpDateEnd;

    /**
     * Database Column Remarks:
     *   跟进时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.follow_up_date
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date followUpDate;

    /**
     * Database Column Remarks:
     *   跟进方式
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.follow_up_type
     *
     * @mbg.generated
     */
    private Long followUpType;

    /**
     * Database Column Remarks:
     *   跟进结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.follow_up_result
     *
     * @mbg.generated
     */
    private String followUpResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_follow_up
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date nextTimeBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_follow_up
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date nextTimeEnd;

    /**
     * Database Column Remarks:
     *   下次跟进时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.next_time
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date nextTime;

    /**
     * Database Column Remarks:
     *   客户等级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.level
     *
     * @mbg.generated
     */
    private Long level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_follow_up
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date settingTimeBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_follow_up
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date settingTimeEnd;

    /**
     * Database Column Remarks:
     *   预计入驻时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.setting_time
     *
     * @mbg.generated
     */
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")
    private Date settingTime;

    /**
     * Database Column Remarks:
     *   附件ID # 分割
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_follow_up.attachment
     *
     * @mbg.generated
     */
    private String attachment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_follow_up
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Long key) {
        this.id = key;
    }

    @Override
    public Long getKey() {
        return id;
    }
}