package com.xstudio.crm.model;

import com.xstudio.tool.utils.BaseModelObject2;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table file
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class File extends BaseModelObject2<Long> implements Serializable {
    /**
     * Database Column Remarks:
     *   文件ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_id
     *
     * @mbg.generated
     */
    private Long fileId;

    /**
     * Database Column Remarks:
     *   文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   文件大小Byte
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_size
     *
     * @mbg.generated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table file
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Long key) {
        this.fileId = key;
    }

    @Override
    public Long getKey() {
        return fileId;
    }
}