package com.xstudio.crm.model;

import com.xstudio.tool.utils.BaseModelObject2;
import java.io.Serializable;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table groups
 */
@Data
@EqualsAndHashCode(callSuper = false)
public class Groups extends BaseModelObject2<Long> implements Serializable {

    /**
     * Database Column Remarks:
     *   ����
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.item_id
     *
     * @mbg.generated
     */
    private Long itemId;

    /**
     * Database Column Remarks:
     *   ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.item_name
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     * Database Column Remarks:
     *   �������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.item_code
     *
     * @mbg.generated
     */
    private String itemCode;

    /**
     * Database Column Remarks:
     *   ��������
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table groups
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    @Override
    public void setKey(Long key) {
        this.itemId = key;
    }

    @Override
    public Long getKey() {
        return itemId;
    }
}
